Repository adalitayoung/SoftwareStudio2A, pull requests merged in 2020-10, with the labels that each got.

#52 update homepage
  AllocationApp/client/src/components/Home.jsx
  AllocationApp/client/src/style/style.css
Labels: frontend

#54 Updated temp-student model to save multipal technical background values
  AllocationApp/server/models/temp-student-model.js
Labels: Backend

#55 Addded getRolesForBackground api to be used in update preference page.
  AllocationApp/client/src/api/index.js
  AllocationApp/server/controllers/projectRoles-ctrl.js
  AllocationApp/server/routes/project-router.js
Labels: Backend, frontend

#56 Add students to project manually
  AllocationApp/client/src/api/index.js
  AllocationApp/server/controllers/project-ctrl.js
  AllocationApp/server/controllers/user-ctrl.js
  AllocationApp/server/routes/project-router.js
Labels: Backend, frontend

#57 Added addStudentToProjectManually in exports in index.js
  AllocationApp/client/src/api/index.js
Labels: frontend

#58 stupid typo
  AllocationApp/client/src/api/index.js
Labels: bug, frontend

#59 Output to excel
  AllocationApp/client/src/api/index.js
  AllocationApp/server/controllers/outputToExcel.js
  AllocationApp/server/package-lock.json
  AllocationApp/server/package.json
  AllocationApp/server/routes/user-router.js
Labels: Backend

#60 Added showMyClasses API to return all the class enrolments of a student
  AllocationApp/client/src/api/index.js
  AllocationApp/server/controllers/class-ctrl.js
  AllocationApp/server/controllers/user-ctrl.js
  AllocationApp/server/routes/class-router.js
Labels: Backend

#70 Commented out buggy code which was triggering on its own to generate …
  AllocationApp/server/controllers/outputToExcel.js
Labels: Backend, bug
